name: build-on-push

on: [push]

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Maven
        uses: s4u/setup-maven-action@v1.14.0
        with:
          java-distribution: corretto
          java-version: 11
          maven-version: 3.6.0
      - name: "Cache local Maven"
        uses: actions/cache@4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: Execute tests and compute coverage
        run: mvn clean test
      - name: Generate coverage report
        run: mvn jacoco:report
  publish-job:
      runs-on: ubuntu-latest
      needs: [build_and_test]
      steps:
        - uses: actions/checkout@v4
        - uses: actions/setup-java@v4
          with:
            distribution: corretto
            java-version: 11
        - run: mvn -B package --file pom.xml -DskipTests
        - run: mkdir staging && cp **/target/*jar-with-dependencies.jar staging
        - uses: actions/upload-artifact@v1
          with:
            name: Package
            path: staging
